/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardClipStudioRouteImport } from './routes/dashboard/clip-studio'
import { Route as DashboardIngestRouteImport } from './routes/dashboard/ingest'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardWorkspaceRouteImport } from './routes/dashboard/workspace'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClipStudioRoute = DashboardClipStudioRouteImport.update({
  id: '/dashboard/clip-studio',
  path: '/dashboard/clip-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIngestRoute = DashboardIngestRouteImport.update({
  id: '/dashboard/ingest',
  path: '/dashboard/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/dashboard/jobs',
  path: '/dashboard/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/dashboard/library',
  path: '/dashboard/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/dashboard/workspace',
  path: '/dashboard/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/clip-studio': typeof DashboardClipStudioRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/clip-studio': typeof DashboardClipStudioRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/clip-studio': typeof DashboardClipStudioRoute
  '/dashboard/ingest': typeof DashboardIngestRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/api/$'
    | '/dashboard/clip-studio'
    | '/dashboard/ingest'
    | '/dashboard/jobs'
    | '/dashboard/library'
    | '/dashboard/workspace'
    | '/invite/$token'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/api/$'
    | '/dashboard/clip-studio'
    | '/dashboard/ingest'
    | '/dashboard/jobs'
    | '/dashboard/library'
    | '/dashboard/workspace'
    | '/invite/$token'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/jobs'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/api/$'
    | '/dashboard/clip-studio'
    | '/dashboard/ingest'
    | '/dashboard/jobs'
    | '/dashboard/library'
    | '/dashboard/workspace'
    | '/invite/$token'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DashboardClipStudioRoute: typeof DashboardClipStudioRoute
  DashboardIngestRoute: typeof DashboardIngestRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clip-studio': {
      id: '/dashboard/clip-studio'
      path: '/dashboard/clip-studio'
      fullPath: '/dashboard/clip-studio'
      preLoaderRoute: typeof DashboardClipStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ingest': {
      id: '/dashboard/ingest'
      path: '/dashboard/ingest'
      fullPath: '/dashboard/ingest'
      preLoaderRoute: typeof DashboardIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/dashboard/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/dashboard/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspace': {
      id: '/dashboard/workspace'
      path: '/dashboard/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  DashboardClipStudioRoute: DashboardClipStudioRoute,
  DashboardIngestRoute: DashboardIngestRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
  InviteTokenRoute: InviteTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
